{% set name = "pdb2sql" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdb2sql-{{ version }}.tar.gz
  sha256: 51e882cf0326130b4cd7223692350aa027e6be5141c85cad471da5df9d7fa7dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas

test:
  source_files:
    - pdb2sql
    - test
  imports:
    - pdb2sql
  commands:
    - pip check
    - pytest ./test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/DeepRank/pdb2sql
  summary: PDB parser using SQL queries
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - gcroci2
